### ISSUE TITLE
Icon and name

### ISSUE THREAD

**Issue by alterxyz** [pragnyanramtha/dify-plugin-animo#1]
Please modify the icon and display name (provider/animo_visuals.yaml)

```
  label:
    en_US: "animo_visuals"
    zh_Hans: "animo_visuals"
    pt_BR: "animo_visuals"
```
